[server]
maxUploadSize = 1024

[theme]
primaryColor        = "#16352e"
backgroundColor     = "#f7f1e3"
secondaryBackgroundColor = "#e8dece"
textColor           = "#2b2825"
font                = "sans serif"
